insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (36.9, 'Coca Cola', 1);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (35.2, 'Pepsi', 2);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (12.7, 'Voda s citrónem', 3);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (14.8, 'Minerální voda', 4);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (15.6, 'Čaj', 5);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (17.4, 'Káva', 6);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (33.5, 'Vodka', 7);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (17.1, 'Pivo Plzeň 11°', 8);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (18.5, 'Pivo Kozel 11°', 9);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (60.7, 'Cibulová polévka', 10);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (20.0, 'Zelná polevka s klobásou', 11);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (96.7, 'Smažený květák', 12);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (140.8, 'Kuřecí čína', 13);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (89.6, 'Smažený sýr', 14);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (128.9, 'Medailonky z veřové panenky', 15);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (115.0, 'Kuřecí prsíčko plněné rajčaty', 16);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (139.9, 'Těstoviny zapečené s kuřecím masem', 17);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (136.5, 'Holandský řízek', 18);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (123.9, 'Krůtí na divoko', 19);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (125.8, 'Smažené žampiony', 20);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (166.2, 'Mexické fazole', 21);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (141.4, 'Bramborový guláš', 22);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (113.4, 'Drůbeží játra', 23);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (99.8, 'Zapečená žemlovka', 24);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (127.1, 'Karbanátky', 25);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (23.9, 'Hranolky', 26);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (21.9, 'Americké brambory', 27);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (23.8, 'Krokety', 28);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (20.8, 'Rýže', 29);
insert into "Polozka_menu" ("Cena", "Nazev", "Polozka_menuID") values (21.3, 'Těstoviny', 30);