/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 04-pro-2018 12:55:05 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS r_stul_rezervace_id_seq
;

DROP SEQUENCE IF EXISTS r_ucet_stul_id_seq
;

DROP SEQUENCE IF EXISTS rezervace_rezervaceid_seq
;

DROP SEQUENCE IF EXISTS stav_polozky_stav_polozkyid_seq
;

DROP SEQUENCE IF EXISTS stul_stulid_seq
;

DROP SEQUENCE IF EXISTS ucet_ucetid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "R_Stul_Rezervace" CASCADE
;

DROP TABLE IF EXISTS "R_Ucet_Stul" CASCADE
;

DROP TABLE IF EXISTS "Rezervace" CASCADE
;

DROP TABLE IF EXISTS "Stav_polozky" CASCADE
;

DROP TABLE IF EXISTS "Stul" CASCADE
;

DROP TABLE IF EXISTS "Ucet" CASCADE
;

/* Create Tables */

CREATE TABLE "R_Stul_Rezervace"
(
	"RezervaceID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_stul_rezervace_id_seq"'::text)::regclass)
)
;

CREATE TABLE "R_Ucet_Stul"
(
	"UcetID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_ucet_stul_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Rezervace"
(
	"Cas_zahajeni" timestamp without time zone NOT NULL,	-- Presny cas, na kdy je dana rezervace obsazena
	"Cas_ukonceni" timestamp without time zone NULL,
	"Jmeno" varchar(50) NOT NULL,	-- Jmeno, na koho ma rezervace zaznamenana
	"Pocet_osob" numeric(32) NULL,	-- Pocet udava kolik osob bude ocekavano
	"RezervaceID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"rezervace_rezervaceid_seq"'::text)::regclass)
)
;

CREATE TABLE "Stav_polozky"
(
	"Cas_vytvoreni" timestamp without time zone NOT NULL,
	"Stav" varchar(10) NULL,
	"Stav_polozkyID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stav_polozky_stav_polozkyid_seq"'::text)::regclass),
	"Polozka_menuID" numeric(32) NULL,
	"UcetID" numeric(32) NULL
)
;

CREATE TABLE "Stul"
(
	"Cislo_stolu" varchar(5) NOT NULL,	-- Identifikace konkretniho stolu
	"Pocet_mist" numeric(8,2) NULL,	--  Udava kapacitu u daneho stolu
	"StulID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stul_stulid_seq"'::text)::regclass)
)
;

CREATE TABLE "Ucet"
(
	"Datum_vytvoreni" timestamp without time zone NOT NULL,	-- Datum, kdy byl pro zakaznika vystaven ucet
	"Mena" varchar(3) NULL,	-- Mena (CZK/USD/EUR...), ve ktere zakaznik platil
	"Platba_kartou" char(1) NOT NULL,
	"Sleva" real NULL,	-- Informace o tom, zda byla poskytnuta zakaznikovi sleva
	"UcetID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"ucet_ucetid_seq"'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "PK_R_Stul_Rezervace"
	PRIMARY KEY ("ID")
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "PK_R_Ucet_Stul"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "PK_Rezervace"
	PRIMARY KEY ("RezervaceID")
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "PK_Stav_polozky"
	PRIMARY KEY ("Stav_polozkyID")
;

ALTER TABLE "Stul" ADD CONSTRAINT "PK_Stul"
	PRIMARY KEY ("StulID")
;

ALTER TABLE "Ucet" ADD CONSTRAINT "PK_Ucet"
	PRIMARY KEY ("UcetID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_REZERVACE"
	FOREIGN KEY ("RezervaceID") REFERENCES "Rezervace" ("RezervaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_UCET"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_ma_stav"
	FOREIGN KEY ("Polozka_menuID") REFERENCES "Polozka_menu" ("Polozka_menuID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_obsahuje"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE r_stul_rezervace_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE r_ucet_stul_id_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Rezervace"
	IS 'Rezervace je vytvorena pro konkretniho zakaznika na konkretni cas a pocet osob, pote je prirazena konkretnimu stolu nebo stolum, tak aby stoly mely dostatecnou kapacitu pro pocet osob.'
;

COMMENT ON COLUMN "Rezervace"."Cas_zahajeni"
	IS 'Presny cas, na kdy je dana rezervace obsazena'
;

COMMENT ON COLUMN "Rezervace"."Jmeno"
	IS 'Jmeno, na koho ma rezervace zaznamenana'
;

COMMENT ON COLUMN "Rezervace"."Pocet_osob"
	IS 'Pocet udava kolik osob bude ocekavano'
;

CREATE SEQUENCE rezervace_rezervaceid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stav_polozky"
	IS 'Pri pridavani polozky z menu na ucet je potreba udrzovat cas jeji pridani a take jeji stav, tzn. zda se pripravuje nebo byla zakaznikovi vydana.'
;

CREATE SEQUENCE stav_polozky_stav_polozkyid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stul"
	IS 'Stul ma urcity pocet mist a jednoznacny identifikator (cislo stolu), aby cisnici vedeli, o ktery stul jde. Stolu je pak prirazen ucet, pokud u nej sedi zakaznik, ktery si neco objednal. Stul muze byt take rezervovana zakaznikem na urcitou dobu a pro urcity pocet osob.'
;

COMMENT ON COLUMN "Stul"."Cislo_stolu"
	IS 'Identifikace konkretniho stolu'
;

COMMENT ON COLUMN "Stul"."Pocet_mist"
	IS '
Udava kapacitu u daneho stolu'
;

CREATE SEQUENCE stul_stulid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Ucet"
	IS 'Na ucet se pripisuji polozky, ktere si zakaznik objednal. Udzuje si informaci o dobe vytvoreni (cas prvni objednavky), zda je na tento ucet prirazena nejaka sleva a zda byla castka uhrazena kartou nebo v hotovosti. Ucet je prirazen konkretnimu stolu a obsahuje polozky z menu.'
;

COMMENT ON COLUMN "Ucet"."Datum_vytvoreni"
	IS 'Datum, kdy byl pro zakaznika vystaven ucet'
;

COMMENT ON COLUMN "Ucet"."Mena"
	IS 'Mena (CZK/USD/EUR...), ve ktere zakaznik platil'
;

COMMENT ON COLUMN "Ucet"."Sleva"
	IS 'Informace o tom, zda byla poskytnuta zakaznikovi sleva'
;

CREATE SEQUENCE ucet_ucetid_seq INCREMENT 1 START 1
;
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 04-pro-2018 12:55:25 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS r_stul_rezervace_id_seq
;

DROP SEQUENCE IF EXISTS r_ucet_stul_id_seq
;

DROP SEQUENCE IF EXISTS rezervace_rezervaceid_seq
;

DROP SEQUENCE IF EXISTS stav_polozky_stav_polozkyid_seq
;

DROP SEQUENCE IF EXISTS stul_stulid_seq
;

DROP SEQUENCE IF EXISTS ucet_ucetid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "R_Stul_Rezervace" CASCADE
;

DROP TABLE IF EXISTS "R_Ucet_Stul" CASCADE
;

DROP TABLE IF EXISTS "Rezervace" CASCADE
;

DROP TABLE IF EXISTS "Stav_polozky" CASCADE
;

DROP TABLE IF EXISTS "Stul" CASCADE
;

DROP TABLE IF EXISTS "Ucet" CASCADE
;

/* Create Tables */

CREATE TABLE "R_Stul_Rezervace"
(
	"RezervaceID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_stul_rezervace_id_seq"'::text)::regclass)
)
;

CREATE TABLE "R_Ucet_Stul"
(
	"UcetID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_ucet_stul_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Rezervace"
(
	"Cas_zahajeni" timestamp without time zone NOT NULL,	-- Presny cas, na kdy je dana rezervace obsazena
	"Cas_ukonceni" timestamp without time zone NULL,
	"Jmeno" varchar(50) NOT NULL,	-- Jmeno, na koho ma rezervace zaznamenana
	"Pocet_osob" numeric(32) NULL,	-- Pocet udava kolik osob bude ocekavano
	"RezervaceID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"rezervace_rezervaceid_seq"'::text)::regclass)
)
;

CREATE TABLE "Stav_polozky"
(
	"Cas_vytvoreni" timestamp without time zone NOT NULL,
	"Stav" varchar(10) NULL,
	"Stav_polozkyID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stav_polozky_stav_polozkyid_seq"'::text)::regclass),
	"Polozka_menuID" numeric(32) NULL,
	"UcetID" numeric(32) NULL
)
;

CREATE TABLE "Stul"
(
	"Cislo_stolu" varchar(5) NOT NULL,	-- Identifikace konkretniho stolu
	"Pocet_mist" numeric(8,2) NULL,	--  Udava kapacitu u daneho stolu
	"StulID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stul_stulid_seq"'::text)::regclass)
)
;

CREATE TABLE "Ucet"
(
	"Datum_vytvoreni" timestamp without time zone NOT NULL,	-- Datum, kdy byl pro zakaznika vystaven ucet
	"Mena" varchar(3) NULL,	-- Mena (CZK/USD/EUR...), ve ktere zakaznik platil
	"Platba_kartou" char(1) NOT NULL,
	"Sleva" real NULL,	-- Informace o tom, zda byla poskytnuta zakaznikovi sleva
	"UcetID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"ucet_ucetid_seq"'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "PK_R_Stul_Rezervace"
	PRIMARY KEY ("ID")
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "PK_R_Ucet_Stul"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "PK_Rezervace"
	PRIMARY KEY ("RezervaceID")
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "PK_Stav_polozky"
	PRIMARY KEY ("Stav_polozkyID")
;

ALTER TABLE "Stul" ADD CONSTRAINT "PK_Stul"
	PRIMARY KEY ("StulID")
;

ALTER TABLE "Ucet" ADD CONSTRAINT "PK_Ucet"
	PRIMARY KEY ("UcetID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_REZERVACE"
	FOREIGN KEY ("RezervaceID") REFERENCES "Rezervace" ("RezervaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_UCET"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_ma_stav"
	FOREIGN KEY ("Polozka_menuID") REFERENCES "Polozka_menu" ("Polozka_menuID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_obsahuje"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE r_stul_rezervace_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE r_ucet_stul_id_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Rezervace"
	IS 'Rezervace je vytvorena pro konkretniho zakaznika na konkretni cas a pocet osob, pote je prirazena konkretnimu stolu nebo stolum, tak aby stoly mely dostatecnou kapacitu pro pocet osob.'
;

COMMENT ON COLUMN "Rezervace"."Cas_zahajeni"
	IS 'Presny cas, na kdy je dana rezervace obsazena'
;

COMMENT ON COLUMN "Rezervace"."Jmeno"
	IS 'Jmeno, na koho ma rezervace zaznamenana'
;

COMMENT ON COLUMN "Rezervace"."Pocet_osob"
	IS 'Pocet udava kolik osob bude ocekavano'
;

CREATE SEQUENCE rezervace_rezervaceid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stav_polozky"
	IS 'Pri pridavani polozky z menu na ucet je potreba udrzovat cas jeji pridani a take jeji stav, tzn. zda se pripravuje nebo byla zakaznikovi vydana.'
;

CREATE SEQUENCE stav_polozky_stav_polozkyid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stul"
	IS 'Stul ma urcity pocet mist a jednoznacny identifikator (cislo stolu), aby cisnici vedeli, o ktery stul jde. Stolu je pak prirazen ucet, pokud u nej sedi zakaznik, ktery si neco objednal. Stul muze byt take rezervovana zakaznikem na urcitou dobu a pro urcity pocet osob.'
;

COMMENT ON COLUMN "Stul"."Cislo_stolu"
	IS 'Identifikace konkretniho stolu'
;

COMMENT ON COLUMN "Stul"."Pocet_mist"
	IS '
Udava kapacitu u daneho stolu'
;

CREATE SEQUENCE stul_stulid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Ucet"
	IS 'Na ucet se pripisuji polozky, ktere si zakaznik objednal. Udzuje si informaci o dobe vytvoreni (cas prvni objednavky), zda je na tento ucet prirazena nejaka sleva a zda byla castka uhrazena kartou nebo v hotovosti. Ucet je prirazen konkretnimu stolu a obsahuje polozky z menu.'
;

COMMENT ON COLUMN "Ucet"."Datum_vytvoreni"
	IS 'Datum, kdy byl pro zakaznika vystaven ucet'
;

COMMENT ON COLUMN "Ucet"."Mena"
	IS 'Mena (CZK/USD/EUR...), ve ktere zakaznik platil'
;

COMMENT ON COLUMN "Ucet"."Sleva"
	IS 'Informace o tom, zda byla poskytnuta zakaznikovi sleva'
;

CREATE SEQUENCE ucet_ucetid_seq INCREMENT 1 START 1
;
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 04-pro-2018 12:54:49 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS r_stul_rezervace_id_seq
;

DROP SEQUENCE IF EXISTS r_ucet_stul_id_seq
;

DROP SEQUENCE IF EXISTS rezervace_rezervaceid_seq
;

DROP SEQUENCE IF EXISTS stav_polozky_stav_polozkyid_seq
;

DROP SEQUENCE IF EXISTS stul_stulid_seq
;

DROP SEQUENCE IF EXISTS ucet_ucetid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "R_Stul_Rezervace" CASCADE
;

DROP TABLE IF EXISTS "R_Ucet_Stul" CASCADE
;

DROP TABLE IF EXISTS "Rezervace" CASCADE
;

DROP TABLE IF EXISTS "Stav_polozky" CASCADE
;

DROP TABLE IF EXISTS "Stul" CASCADE
;

DROP TABLE IF EXISTS "Ucet" CASCADE
;

/* Create Tables */

CREATE TABLE "R_Stul_Rezervace"
(
	"RezervaceID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_stul_rezervace_id_seq"'::text)::regclass)
)
;

CREATE TABLE "R_Ucet_Stul"
(
	"UcetID" numeric(32) NULL,
	"StulID" numeric(32) NULL,
	"ID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"r_ucet_stul_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Rezervace"
(
	"Cas_zahajeni" timestamp without time zone NOT NULL,	-- Presny cas, na kdy je dana rezervace obsazena
	"Cas_ukonceni" timestamp without time zone NULL,
	"Jmeno" varchar(50) NOT NULL,	-- Jmeno, na koho ma rezervace zaznamenana
	"Pocet_osob" numeric(32) NULL,	-- Pocet udava kolik osob bude ocekavano
	"RezervaceID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"rezervace_rezervaceid_seq"'::text)::regclass)
)
;

CREATE TABLE "Stav_polozky"
(
	"Cas_vytvoreni" timestamp without time zone NOT NULL,
	"Stav" varchar(10) NULL,
	"Stav_polozkyID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stav_polozky_stav_polozkyid_seq"'::text)::regclass),
	"Polozka_menuID" numeric(32) NULL,
	"UcetID" numeric(32) NULL
)
;

CREATE TABLE "Stul"
(
	"Cislo_stolu" varchar(5) NOT NULL,	-- Identifikace konkretniho stolu
	"Pocet_mist" numeric(8,2) NULL,	--  Udava kapacitu u daneho stolu
	"StulID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"stul_stulid_seq"'::text)::regclass)
)
;

CREATE TABLE "Ucet"
(
	"Datum_vytvoreni" timestamp without time zone NOT NULL,	-- Datum, kdy byl pro zakaznika vystaven ucet
	"Mena" varchar(3) NULL,	-- Mena (CZK/USD/EUR...), ve ktere zakaznik platil
	"Platba_kartou" char(1) NOT NULL,
	"Sleva" real NULL,	-- Informace o tom, zda byla poskytnuta zakaznikovi sleva
	"UcetID" numeric(32) NOT NULL   DEFAULT NEXTVAL(('"ucet_ucetid_seq"'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "PK_R_Stul_Rezervace"
	PRIMARY KEY ("ID")
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "PK_R_Ucet_Stul"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "PK_Rezervace"
	PRIMARY KEY ("RezervaceID")
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "PK_Stav_polozky"
	PRIMARY KEY ("Stav_polozkyID")
;

ALTER TABLE "Stul" ADD CONSTRAINT "PK_Stul"
	PRIMARY KEY ("StulID")
;

ALTER TABLE "Ucet" ADD CONSTRAINT "PK_Ucet"
	PRIMARY KEY ("UcetID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Stul_Rezervace" ADD CONSTRAINT "FK_je_prirazena_REZERVACE"
	FOREIGN KEY ("RezervaceID") REFERENCES "Rezervace" ("RezervaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_UCET"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "R_Ucet_Stul" ADD CONSTRAINT "FK_je_prirazen_STUL"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_ma_stav"
	FOREIGN KEY ("Polozka_menuID") REFERENCES "Polozka_menu" ("Polozka_menuID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stav_polozky" ADD CONSTRAINT "FK_STAV_POLOZKY_obsahuje"
	FOREIGN KEY ("UcetID") REFERENCES "Ucet" ("UcetID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE r_stul_rezervace_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE r_ucet_stul_id_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Rezervace"
	IS 'Rezervace je vytvorena pro konkretniho zakaznika na konkretni cas a pocet osob, pote je prirazena konkretnimu stolu nebo stolum, tak aby stoly mely dostatecnou kapacitu pro pocet osob.'
;

COMMENT ON COLUMN "Rezervace"."Cas_zahajeni"
	IS 'Presny cas, na kdy je dana rezervace obsazena'
;

COMMENT ON COLUMN "Rezervace"."Jmeno"
	IS 'Jmeno, na koho ma rezervace zaznamenana'
;

COMMENT ON COLUMN "Rezervace"."Pocet_osob"
	IS 'Pocet udava kolik osob bude ocekavano'
;

CREATE SEQUENCE rezervace_rezervaceid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stav_polozky"
	IS 'Pri pridavani polozky z menu na ucet je potreba udrzovat cas jeji pridani a take jeji stav, tzn. zda se pripravuje nebo byla zakaznikovi vydana.'
;

CREATE SEQUENCE stav_polozky_stav_polozkyid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Stul"
	IS 'Stul ma urcity pocet mist a jednoznacny identifikator (cislo stolu), aby cisnici vedeli, o ktery stul jde. Stolu je pak prirazen ucet, pokud u nej sedi zakaznik, ktery si neco objednal. Stul muze byt take rezervovana zakaznikem na urcitou dobu a pro urcity pocet osob.'
;

COMMENT ON COLUMN "Stul"."Cislo_stolu"
	IS 'Identifikace konkretniho stolu'
;

COMMENT ON COLUMN "Stul"."Pocet_mist"
	IS '
Udava kapacitu u daneho stolu'
;

CREATE SEQUENCE stul_stulid_seq INCREMENT 1 START 1
;

COMMENT ON TABLE "Ucet"
	IS 'Na ucet se pripisuji polozky, ktere si zakaznik objednal. Udzuje si informaci o dobe vytvoreni (cas prvni objednavky), zda je na tento ucet prirazena nejaka sleva a zda byla castka uhrazena kartou nebo v hotovosti. Ucet je prirazen konkretnimu stolu a obsahuje polozky z menu.'
;

COMMENT ON COLUMN "Ucet"."Datum_vytvoreni"
	IS 'Datum, kdy byl pro zakaznika vystaven ucet'
;

COMMENT ON COLUMN "Ucet"."Mena"
	IS 'Mena (CZK/USD/EUR...), ve ktere zakaznik platil'
;

COMMENT ON COLUMN "Ucet"."Sleva"
	IS 'Informace o tom, zda byla poskytnuta zakaznikovi sleva'
;

CREATE SEQUENCE ucet_ucetid_seq INCREMENT 1 START 1
;
