/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 27-lis-2018 18:01:58 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Triggers, Sequences for Autonumber Columns */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Menu_MenuID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Menu_MenuID"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Menu_MenuID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Menu_MenuID"'; 
END IF; 
END;
/


DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Polozka_menu_Polozka_menuID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Polozka_menu_Polozka_menuID"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Polozka_menu_Polozka_menuID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Polozka_menu_Polozka_menuID"'; 
END IF; 
END;
/


DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Popularita_PopularitaID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Popularita_PopularitaID"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Popularita_PopularitaID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Popularita_PopularitaID"'; 
END IF; 
END;
/


DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Typ_TypID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Typ_TypID"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Typ_TypID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Typ_TypID"'; 
END IF; 
END;
/


/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Menu" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Polozka_menu" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Popularita" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "R_PolozkaMenu_Menu" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "R_PolozkaMenu_Typ" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Typ" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "Menu"
(
	"Jazyk" VARCHAR(50) NULL,	-- Informace v jakem jazyce je jidelnicek napsan
	"Platne_do" DATE NULL,
	"Platne_od" DATE NULL,	-- Aktualni datum,pro ktery je jidelnicek platny
	"MenuID" NUMBER(32) NOT NULL
)
;

CREATE TABLE  "Polozka_menu"
(
	"Cena" FLOAT(32) NOT NULL,
	"Nazev" VARCHAR(100) NULL,
	"Polozka_menuID" NUMBER(32) NOT NULL
)
;

CREATE TABLE  "Popularita"
(
	"Datum" DATE NULL,
	"Hodnota" NUMBER(8,2) NULL,
	"PopularitaID" NUMBER(32) NOT NULL,
	"Polozka_menuID" NUMBER(32) NULL
)
;

CREATE TABLE  "R_PolozkaMenu_Menu"
(
	"MenuID" NUMBER(32) NULL,
	"Polozka_menuID" NUMBER(32) NULL,
	"ID" NUMBER(32) NOT NULL
)
;

CREATE TABLE  "R_PolozkaMenu_Typ"
(
	"Polozka_menuID" NUMBER(32) NULL,
	"TypID" NUMBER(32) NULL,
	"ID" NUMBER(32) NOT NULL
)
;

CREATE TABLE  "Typ"
(
	"Nazev" VARCHAR(50) NULL,
	"TypID" NUMBER(32) NOT NULL
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "Menu" IS 'Menu obsahuje polozky menu, ze kterych si zakaznici vybiraji sve objednavky. Menu ma urcitou platnost a jazyk.'
;


COMMENT ON COLUMN  "Menu"."Jazyk" IS 'Informace v jakem jazyce je jidelnicek napsan';

COMMENT ON COLUMN  "Menu"."Platne_od" IS 'Aktualni datum,pro ktery je jidelnicek platny';

CREATE SEQUENCE "SEQ_Menu_MenuID" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Menu_MenuID" 
	BEFORE INSERT 
	ON "Menu" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Menu_MenuID".NEXTVAL 
		INTO :NEW."MenuID" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "Polozka_menu" IS 'Polozka menu je konkretni polozka, kterou si zakaznik muze vybrat z menu a nasledne objednat u cisnika. Kazda takova polozka ma svoji cenu a nazev.'
;


CREATE SEQUENCE "SEQ_Polozka_menu_Polozka_menuID" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Polozka_menu_Polozka_menuID" 
	BEFORE INSERT 
	ON "Polozka_menu" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Polozka_menu_Polozka_menuID".NEXTVAL 
		INTO :NEW."Polozka_menuID" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "Popularita" IS 'U kazdeho polozky menu je potreba udrzovat jeji popularitu. Tato popularita se vyuziva pri sestavovani denniho menu a je urcovana podle mnozstvi objednavek daneho jidla. Popularita se v case vyviji, proto je u ni potreba udrzovat datum.'
;


CREATE SEQUENCE "SEQ_Popularita_PopularitaID" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Popularita_PopularitaID" 
	BEFORE INSERT 
	ON "Popularita" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Popularita_PopularitaID".NEXTVAL 
		INTO :NEW."PopularitaID" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "Typ" IS 'Polozky menu jsou rozdeleny do urcitych kategorii podle jejich typu - alkohol, napoje, testoviny, polevky,...'
;


CREATE SEQUENCE "SEQ_Typ_TypID" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Typ_TypID" 
	BEFORE INSERT 
	ON "Typ" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Typ_TypID".NEXTVAL 
		INTO :NEW."TypID" 
		FROM DUAL; 
	END;

/


/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Menu" 
 ADD CONSTRAINT "PK_Menu"
	PRIMARY KEY ("MenuID") 
 USING INDEX
;

ALTER TABLE  "Polozka_menu" 
 ADD CONSTRAINT "PK_Polozka_menu"
	PRIMARY KEY ("Polozka_menuID") 
 USING INDEX
;

ALTER TABLE  "Popularita" 
 ADD CONSTRAINT "PK_Popularita"
	PRIMARY KEY ("PopularitaID") 
 USING INDEX
;

ALTER TABLE  "R_PolozkaMenu_Menu" 
 ADD CONSTRAINT "PK_R_PolozkaMenu_Menu"
	PRIMARY KEY ("ID") 
 USING INDEX
;

ALTER TABLE  "R_PolozkaMenu_Typ" 
 ADD CONSTRAINT "PK_R_PolozkaMenu_Typ"
	PRIMARY KEY ("ID") 
 USING INDEX
;

ALTER TABLE  "Typ" 
 ADD CONSTRAINT "PK_Typ"
	PRIMARY KEY ("TypID") 
 USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Popularita" 
 ADD CONSTRAINT "FK_POPULARITA_ma_popularitu"
	FOREIGN KEY ("Polozka_menuID") REFERENCES  "Polozka_menu" ("Polozka_menuID")
;

ALTER TABLE  "R_PolozkaMenu_Menu" 
 ADD CONSTRAINT "FK_jsou_na_POLOZKA_MENU"
	FOREIGN KEY ("Polozka_menuID") REFERENCES  "Polozka_menu" ("Polozka_menuID")
;

ALTER TABLE  "R_PolozkaMenu_Menu" 
 ADD CONSTRAINT "FK_jsou_na_MENU"
	FOREIGN KEY ("MenuID") REFERENCES  "Menu" ("MenuID")
;

ALTER TABLE  "R_PolozkaMenu_Typ" 
 ADD CONSTRAINT "FK_je_typu_TYP"
	FOREIGN KEY ("TypID") REFERENCES  "Typ" ("TypID")
;

ALTER TABLE  "R_PolozkaMenu_Typ" 
 ADD CONSTRAINT "FK_je_typu_POLOZKA_MENU"
	FOREIGN KEY ("Polozka_menuID") REFERENCES  "Polozka_menu" ("Polozka_menuID")
;
